apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bpdm-elastic.fullname" . }}
  labels:
    {{- include "bpdm-elastic.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "bpdm-elastic.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "bpdm-elastic.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: discovery.type
              value: {{ .Values.discoveryType }}
          ports:
            - name: http
              containerPort: 9200
              protocol: TCP
          volumeMounts:
            - mountPath: /usr/share/elasticsearch/data
              name: {{ include "bpdm-elastic.fullname" . }}
              subPath: elastic
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: {{ include "bpdm-elastic.fullname" . }}
          persistentVolumeClaim:
            claimName: {{ include "bpdm-elastic.fullname" . }}

