image:
  tag: "v2.0.1"

springProfiles:
  - int


ingress:
  hosts:
    - host: partners-pool.int.demo.catena-x.net
      paths:
        - path: /
          pathType: Prefix
    - host: catenax-bpdm-int.demo.catena-x.net
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: tls-secret
      hosts:
        - partners-pool.int.demo.catena-x.net
    - secretName: bpdm-int-tls
      hosts:
        - catenax-bpdm-int.demo.catena-x.net

applicationSecret:
  keycloak: <path:bpdm/data/int/pool/keycloak#credentials-secret>
  cdq: <path:bpdm/data/int/pool/cdq#api-key>

applicationConfig: |
  # every hour at minute 30
  bpdm.opensearch.export-scheduler-cron-expr=0 30 * * * *
  # every hour at minute 0
  bpdm.cdq.import-scheduler-cron-expr=0 0 * * * *

postgres:
  auth:
    postgresPassword: <path:bpdm/data/int/pool/postgresql#postgres-password>
    password: <path:bpdm/data/int/pool/postgresql#password>