################################################################################
# Copyright (c) 2021,2024 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License, Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# SPDX-License-Identifier: Apache-2.0
################################################################################

bpdm:
  client:
    orchestrator:
      # Name of the Spring oauth2 client registration entry for connecting to the Orchestrator
      # This registration will be used to configure this application's webclients that want to access the Orchestrator
      oauth2-client-registration: orchestrator-client
      # Whether to enable oauth2 authentication when connecting to the Orchestrator
      security-enabled: true
#
# From here on are framework and dependency configuration
# More information about those properties can be taken from the respective documentation of Spring or the dependency
#
spring:
  security:
    oauth2:
      client:
        provider:
          # Create an oauth2 provider for the pool and infer token issuing uri from the security properties
          # If auth profile is not set use equivalent defaults
          orchestrator-oauth2-provider:
            issuer-uri: ${bpdm.security.auth-server-url:http://localhost:8180}/realms/${bpdm.security.realm:master}
        registration:
          # Register oauth2 client information on how to acquire a token for the Orchestrator
          orchestrator-client:
            # The orchestrator client should use client credentials mechanism to request a token from the provider
            authorization-grant-type: client_credentials
            # Use a default client id for the client credentials request
            client-id: BPDM_ORCHESTRATOR_CLIENT
            # No secret on default (please update credentials for production)
            client-secret:
            # Use the specified provider above to infer the issuing token uri
            provider: orchestrator-oauth2-provider
