image:
  tag: "main"

ingress:
  hosts:
    - host: partners-gate.dev.demo.catena-x.net
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: tls-secret
      hosts:
        - partners-gate.dev.demo.catena-x.net

applicationConfig:
  bpdm:
    security:
      enabled: true
    gate-security:
      pool-security-enabled: true
      oauth2-client-registration: gate-client
    cdq:
      storage: 38d2277e20c730b4b8e8f182adcef7ca
      datasource-legal-entity: 621338451197b7667a5fbda4
      datasource-address: 621338451197b7667a5fbda4
      datasource-site: 621338451197b7667a5fbda4
  keycloak:
    enabled: true
    auth-server-url: https://centralidp.dev.demo.catena-x.net/auth
    realm: CX-Central
    resource: Cl16-CX-BPDMGate
  spring:
    security:
      oauth2:
        client:
          registration:
            gate-client:
              client-id: sa-cl16-cx-1
              authorization-grant-type: client_credentials
              provider: catena-keycloak-provider
          provider:
            catena-keycloak-provider:
              issuer-uri: https://centralidp.dev.demo.catena-x.net/auth/realms/CX-Central
  springdoc:
    swagger-ui:
      oauth:
        client-id: Cl2-CX-Portal

applicationSecrets:
  spring:
    security:
      oauth2:
        client:
          registration:
            gate-client:
              client-secret: <path:bpdm/data/dev/gate/service-account#client-secret>
  bpdm:
    cdq:
      api-key: <path:bpdm/data/dev/gate/cdq#api-key>