name: Vera Code Pipeline Scan
on:
  pull_request:
    types: [ opened, reopened, synchronize ]

jobs:
  analyze:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Package to JAR
        run: ./mvnw -B package

      #Download Vera Code local scanner
      - name: Download the Pipeline Scanner
        uses: wei/curl@master
        with:
          args: -O https://downloads.veracode.com/securityscan/pipeline-scan-LATEST.zip

      #Unzip Vera code scanner
      - name: Unzip the Pipeline Scanner
        # Overwrites files
        # Sometimes there are conflicts, e.g. README.md
        run: unzip -o pipeline-scan-LATEST.zip

      #Verify with Vera Code local scan
      - name: Run Pipeline Scanner
        run: |
          java -Dpipeline.debug=true -jar pipeline-scan.jar \
          --veracode_api_id "${{secrets.VERACODE_API_ID}}" \
          --veracode_api_key "${{secrets.VERACODE_API_KEY}}" \
          --file "target/bpdm.jar" \
          --fail_on_severity="Very High, High" \
          -jo true

      - name: Convert pipeline scan output to SARIF format
        if: always()
        uses: Veracode/veracode-pipeline-scan-results-to-sarif@v0.1.5
        with:
          pipeline-results-json: results.json
          output-results-sarif: veracode-results.sarif
          source-base-path-1: "^com/veracode:src/main/java/com/veracode"
          source-base-path-2: "^WEB-INF:src/main/webapp/WEB-INF"
          finding-rule-level: "3:1:0"

      - name: Upload Veracode sarif file to repository
        uses: github/codeql-action/upload-sarif@v1
        if: always()
        with:
          sarif_file: veracode-results.sarif